import type { ArchiveProject } from "./project-archive";

// Transcribed from the visible project links in Hong Yu's supplied Beacons
// HTML. Only project URLs and copy are retained, not scripts or session data.
// Unknown years and technology stacks are intentionally left unspecified.
export const beaconsProjects: readonly ArchiveProject[] = [
  {
    id: "shape-up",
    name: "Shape Up!",
    year: 2026,
    category: "Games & events",
    description: "Most Entertaining Hack at NUS Hack&Roll 2026.",
    tech: [],
    status: "Most Entertaining Hack",
    github: null,
    website: "https://shape-up-beta.vercel.app/",
  },
  {
    id: "mermurs",
    name: "SYAI MerMurs",
    year: 2025,
    category: "AI & automation",
    description:
      "A Singapore Youth AI project for the AIMM July 2025 SG60 edition.",
    tech: ["TypeScript"],
    status: "Event project",
    github: "https://github.com/UltraRaptorYT/MerMurs",
    website: "https://mermurs.vercel.app/",
  },
  {
    id: "ai-photobooth",
    name: "SYAI AI Photobooth",
    year: 2025,
    category: "AI & automation",
    description: "An AI photobooth project for ATx Summit 2025.",
    tech: ["Next.js", "TypeScript"],
    status: "Event project",
    github: "https://github.com/UltraRaptorYT/AI-Photobooth",
    website: "https://syai-ai-photobooth.vercel.app/",
  },
  {
    id: "whack-the-poisons",
    name: "Whack The Poisons!",
    year: 2025,
    category: "Games & events",
    description: "A game for Vesak Day 2025.",
    tech: ["TypeScript"],
    status: "Event game",
    github: "https://github.com/UltraRaptorYT/BWMVesak2025",
    website: "https://bwm-vesak2025.vercel.app/",
  },
  {
    id: "artificial-failure",
    name: "Art-ificial Failure",
    year: 2025,
    category: "Games & events",
    description: "Best Pre-University Hack at NUS Hack&Roll 2025.",
    tech: [],
    status: "Best Pre-University Hack",
    github: null,
    website: "https://art-ificial-failure.vercel.app/",
  },
  {
    id: "puzzle-hunt-bot",
    name: "BW Monastery Puzzle Hunt Bot",
    year: 2024,
    category: "Games & events",
    description: "A Telegram puzzle-hunt bot for Mid-Autumn Festival 2024.",
    tech: ["Telegram"],
    status: "Event project",
    github: null,
    website: "https://t.me/bwmonastery_bot",
  },
  {
    id: "aivy",
    name: "AiVY",
    year: 2024,
    category: "AI & automation",
    description: "A build for NUS LifeHack 2024.",
    tech: ["TypeScript"],
    status: "Hackathon build",
    github: "https://github.com/UltraRaptorYT/AiVY",
    website: "https://aivy.vercel.app/",
  },
  {
    id: "vr-buddha",
    name: "VR Buddha",
    year: 2024,
    category: "Games & events",
    description: "A VR experience for Vesak Day 2024.",
    tech: ["TypeScript"],
    status: "Event experience",
    github: "https://github.com/UltraRaptorYT/VR-Buddha",
    website: "https://vr-buddha.vercel.app/",
  },
  {
    id: "govguide",
    name: "GovGuide",
    year: 2024,
    category: "Tools",
    description: "A project for HackOMania 2024.",
    tech: [],
    status: "Hackathon build",
    github: null,
    website: "https://gov-guide.vercel.app/",
  },
  {
    id: "cobra-duel",
    name: "A Brilliant Cobra Duel",
    year: 2024,
    category: "Games & events",
    description: "Best Pre-University Hack at NUS Hack&Roll 2024.",
    tech: ["Next.js", "TypeScript"],
    status: "Best Pre-University Hack",
    github:
      "https://github.com/UltraRaptorYT/A-Brilliant-Cobra-Duel_NUS-Hack-Roll-2024",
    website: "https://a-brilliant-cobra-duel.vercel.app/",
  },
  {
    id: "unspoken",
    name: "unspoken.",
    year: 2023,
    category: "Games & events",
    description: "A parent-child OMAK activity.",
    tech: ["TypeScript"],
    status: "Event activity",
    github: "https://github.com/UltraRaptorYT/unspoken",
    website: "https://unspoken-bwm.vercel.app/",
  },
  {
    id: "hexasum",
    name: "HexaSum",
    year: 2023,
    category: "Games & events",
    description: "A browser-based game experiment.",
    tech: ["JavaScript"],
    status: "Experiment",
    github: "https://github.com/UltraRaptorYT/HexaSum",
    website: "https://ultraraptoryt.github.io/HexaSum/",
  },
  {
    id: "arcademy",
    name: "ARcademy",
    year: 2023,
    category: "Tools",
    description:
      "An education hackathon project, listed as champion under EduLearn / Innovate2Educate.",
    tech: ["HTML"],
    status: "Hackathon champion",
    github: "https://github.com/UltraRaptorYT/ARcademy",
    website: "https://ultraraptoryt.github.io/ARcademy/",
  },
  {
    id: "journalink",
    name: "JournaLink",
    year: 2023,
    category: "Tools",
    description: "A project for MindfulHacks 2023.",
    tech: [],
    status: "Hackathon build",
    github: "https://github.com/Thaddeusleewj/MindfulHacks_23/tree/main",
    website: null,
  },
  {
    id: "silverlink",
    name: "SilverLink",
    year: 2023,
    category: "Tools",
    description: "Champion at IdeateCOMM 2023.",
    tech: ["HTML"],
    status: "Hackathon champion",
    github: "https://github.com/UltraRaptorYT/IdeateCOMM2023",
    website: "https://ultraraptoryt.github.io/IdeateCOMM2023/login.html",
  },
  {
    id: "sustainabite",
    name: "SustainaBite",
    year: 2023,
    category: "Tools",
    description: "A project for SUTD What The Hack 2023.",
    tech: [],
    status: "Hackathon build",
    github: null,
    website: "https://sustainabite.onrender.com",
  },
  {
    id: "summy",
    name: "Summy",
    year: 2023,
    category: "AI & automation",
    description: "A project for CloudHacks 2023.",
    tech: [],
    status: "Hackathon build",
    github: "https://github.com/lightningsnorlax/CloudHacks-Summy",
    website: null,
  },
  {
    id: "eduplay",
    name: "EduPlay",
    year: 2023,
    category: "Games & events",
    description: "A project for NUS LifeHack 2023.",
    tech: ["Python"],
    status: "Hackathon build",
    github: "https://github.com/UltraRaptorYT/EduPlay",
    website: "https://devpost.com/software/cotton-pickers-eduplay",
  },
  {
    id: "whos-that-pokemon",
    name: "Who's That Pokémon?",
    year: 2023,
    category: "Games & events",
    description: "A small Pokémon guessing-game project.",
    tech: ["JavaScript"],
    status: "Browser game",
    github: "https://github.com/UltraRaptorYT/Who-s-That-Pokemon",
    website: "https://ultraraptoryt.github.io/Who-s-That-Pokemon/",
  },
  {
    id: "night-walk",
    name: "Night Walk App",
    year: 2023,
    category: "Games & events",
    description:
      "An app for The Singularity Freshman Orientation Camp 2022/23.",
    tech: ["HTML"],
    status: "Event app",
    github: "https://github.com/UltraRaptorYT/SOCC-Night-Walk",
    website: "https://focnightwalk.onrender.com/",
  },
  {
    id: "are-you-smarter-than-ai",
    name: "Are You Smarter Than AI?",
    year: 2023,
    category: "Games & events",
    description: "An early browser experiment built around that question.",
    tech: ["HTML"],
    status: "Experiment",
    github: "https://github.com/UltraRaptorYT/Are-You-Smarter-Than-AI",
    website: "https://areyousmarterthanai.onrender.com/",
  },
  {
    id: "immune",
    name: "Immune",
    year: 2023,
    category: "Tools",
    description: "An early web project from the collection.",
    tech: ["HTML"],
    status: "Public build",
    github: "https://github.com/UltraRaptorYT/Immune",
    website: "https://immune.onrender.com/",
  },
  {
    id: "express-call",
    name: "Express Call",
    year: 2022,
    category: "Tools",
    description: "A Tech4Good project featured on Channel 8.",
    tech: ["Python"],
    status: "Tech4Good project",
    github: "https://github.com/UltraRaptorYT/SUTDWTH22",
    website: "https://express-call.onrender.com/",
  },
  {
    id: "socc-ar",
    name: "SOCC Augmented Reality Game",
    year: 2022,
    category: "Games & events",
    description:
      "An augmented-reality game adventure for the School of Computing Club.",
    tech: ["JavaScript"],
    status: "Event game",
    github: "https://github.com/UltraRaptorYT/ARG",
    website: "https://socc-arg.web.app/",
  },
  {
    id: "picture-hunt",
    name: "Picture Hunt",
    year: 2022,
    category: "Games & events",
    description: "An early picture-hunt web project.",
    tech: ["JavaScript"],
    status: "Browser game",
    github: "https://github.com/UltraRaptorYT/picture-hunt",
    website: "https://picturehunt.onrender.com/",
  },
  {
    id: "dbscan",
    name: "DBSCAN Visualiser",
    year: 2022,
    category: "Data & ML",
    description: "A browser visualisation of DBSCAN clustering.",
    tech: ["JavaScript"],
    status: "Learning tool",
    github: "https://github.com/UltraRaptorYT/DBSCAN-Clustering",
    website: "https://ultraraptoryt.github.io/DBSCAN-Clustering/",
  },
  {
    id: "shiok",
    name: "Shiok!",
    year: 2022,
    category: "Tools",
    description: "Gold winner at the Batey Hackathon.",
    tech: [],
    status: "Gold winner",
    github: null,
    website: "https://shiok.web.app",
  },
  {
    id: "medipill",
    name: "MediPill",
    year: 2022,
    category: "Tools",
    description: "A medication app with a companion administration console.",
    tech: ["HTML"],
    status: "App + admin console",
    github: "https://github.com/UltraRaptorYT/SIP-Medication",
    website: "https://bit.ly/NorthCaresSIP",
    extraLinks: [
      {
        label: "Admin console",
        href: "https://ultraraptoryt.github.io/SIP-Medication/",
      },
    ],
  },
  {
    id: "unicorn-adventure",
    name: "A Unicorn's Adventure",
    year: 2022,
    category: "Games & events",
    description:
      "A project for NUS LifeHack 2022, with an app and video walkthrough.",
    tech: [],
    status: "Hackathon build",
    github: null,
    website: "https://lifehack-nus-2022.vercel.app/",
    extraLinks: [{ label: "Watch demo", href: "https://youtu.be/1NT2MHYKP7Q" }],
  },
  {
    id: "flip-the-card",
    name: "Flip the Card Game",
    year: 2022,
    category: "Games & events",
    description:
      "A game for the Circus Extravaganza Freshman Orientation Camp 2021/22.",
    tech: ["JavaScript"],
    status: "Event game",
    github: "https://github.com/UltraRaptorYT/Flip-The-Card-FOC-Game",
    website: "https://ultraraptoryt.github.io/Flip-The-Card-FOC-Game/",
  },
  {
    id: "job-eduperience",
    name: "Job Eduperience",
    year: 2022,
    category: "Tools",
    description: "A project for the NUS Digital Futurist Challenge.",
    tech: ["JavaScript"],
    status: "Challenge project",
    github: "https://github.com/UltraRaptorYT/NUS-DFC",
    website: "https://ultraraptoryt.github.io/NUS-DFC/",
  },
  {
    id: "give-me-a-brieck",
    name: "Give Me a Brieck",
    year: 2021,
    category: "Games & events",
    description: "First place at DSAC Makerspace.",
    tech: ["Python"],
    status: "1st place",
    github: "https://github.com/UltraRaptorYT/Give-me-a-brieck",
    website: null,
  },
  {
    id: "grammar-garden",
    name: "Grammar Garden",
    year: 2021,
    category: "AI & automation",
    description: "A project for the AISG Student Hackathon 2021.",
    tech: ["Python"],
    status: "Hackathon build",
    github: "https://github.com/UltraRaptorYT/Grammar-Garden",
    website: null,
  },
  {
    id: "storyage",
    name: "StoryAge",
    year: 2021,
    category: "Tools",
    description: "A finalist at FIT Hackathon 2021.",
    tech: ["HTML"],
    status: "Hackathon finalist",
    github: "https://github.com/UltraRaptorYT/FITHackathon",
    website: null,
  },
  {
    id: "soenvirofri",
    name: "SoEnviroFri",
    year: 2021,
    category: "Tools",
    description: "A project for SUTD What The Hack 2021.",
    tech: ["JavaScript"],
    status: "Hackathon build",
    github: "https://github.com/UltraRaptorYT/SoEnviroFri",
    website: "https://devpost.com/software/sofri",
  },
  {
    id: "cosmic-chaos",
    name: "Cosmic Chaos",
    year: 2021,
    category: "Games & events",
    description: "A game for Brackeys Game Jam 2021.",
    tech: [],
    status: "Game jam build",
    github: null,
    website: "https://itch.io/jam/brackeys-6/rate/1177618",
  },
  {
    id: "jurassic-rush",
    name: "Sofri: Jurassic Rush",
    year: 2021,
    category: "Games & events",
    description:
      "A dungeon-and-boss game where answering questions helps defeat the bosses. Built for NUS LifeHack 2021.",
    tech: ["JavaScript"],
    status: "Hackathon build",
    github: "https://github.com/UltraRaptorYT/Sofri-025-JurassicRush",
    website: "https://devpost.com/software/sofri-025",
  },
  {
    id: "freezing-frost",
    name: "Freezing Frost",
    year: 2020,
    category: "Games & events",
    description: "A Core game for Global Game Jam Holiday Jam 2020.",
    tech: ["Core"],
    status: "Game jam build",
    github: null,
    website: "https://www.coregames.com/games/127932/frosty-snowball",
  },
  {
    id: "blazing-inferno",
    name: "Blazing Inferno",
    year: 2020,
    category: "Games & events",
    description: "A Core game for Students Game Jam 2020.",
    tech: ["Core"],
    status: "Game jam build",
    github: null,
    website: "https://www.coregames.com/games/777c6c/blazing-inferno",
  },
  {
    id: "dr-go",
    name: "DR Go",
    year: null,
    category: "Tools",
    description: "A project for NTU iNTUition v9.0.",
    tech: [],
    status: "Hackathon build",
    github: null,
    website: "https://drgo.onrender.com/",
  },
  {
    id: "robotech",
    name: "RoboTech Chatbot",
    year: null,
    category: "AI & automation",
    description: "A Smojo chatbot for DeepTech Mover.",
    tech: ["Smojo"],
    status: "Chatbot project",
    github: null,
    website: "https://app.smojo.org/ultraraptor/bot",
  },
  {
    id: "rubi",
    name: "RUBI Chatbot",
    year: null,
    category: "AI & automation",
    description: "A Smojo chatbot, first runner-up at DeepTech Mover.",
    tech: ["Smojo"],
    status: "1st runner-up",
    github: null,
    website: "https://app.smojo.org/eldensim/RUBI",
  },
];

export const elsewhereLinks = [
  { label: "Singapore Youth AI", href: "https://sgyouthai.org/" },
  {
    label: "EAE Tips & Tricks",
    href: "https://www.youtube.com/watch?v=fVuu6RoTlRE&t=4s",
  },
  {
    label: "YouTube",
    href: "https://www.youtube.com/channel/UCM4zdqvxMmRbaBNMs-kcAdA",
  },
  { label: "Instagram", href: "https://instagram.com/therealultraraptor" },
  { label: "TikTok", href: "https://tiktok.com/@sohhongyu" },
  { label: "Tellonym", href: "https://tellonym.me/UltraRaptor" },
] as const;
